Repository iter8-tools/iter8, pull requests merged in 2020-08, with the labels that each got.

#283 New README for controller repo
  README.md
Labels: documentation

#290 Use router id to identify routing rules
  install/helm/iter8-controller/templates/crds/v1alpha2/iter8.tools_experiments.yaml
  pkg/apis/iter8/v1alpha2/experiment_types.go
  pkg/apis/iter8/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/experiment/routing/router/istio/deployment.go
  pkg/controller/experiment/routing/router/istio/helper.go
  pkg/controller/experiment/routing/router/istio/router.go
  pkg/controller/experiment/routing/router/istio/service.go
  test/e2e/kubernetes_test.go
  test/experiment.go
Labels: bug, controller, enhancement

#300 user specified traffic split failure
  pkg/controller/experiment/helper.go
  pkg/controller/experiment/reconcile.go
  pkg/controller/experiment/routing/router/istio/helper.go
Labels: bug
